### ISSUE TITLE
Form with errors is not showing fieldsets according to selection

### ISSUE THREAD

**Issue by falkgeist** [terminal42/contao-conditionalformfields#81] opened 2023-07-24 09:02 UTC
If a form with conditional fieldsets is reloaded with errors, the fields on which the fieldset listens might still be filled/selected, but the corresponding fieldset is not shown accordingly.

In my instance this was the case with a radio ('Yes'/'No') and a fieldset containing a `<input type="tel">` (and of course a submit button).

I selected 'Yes', got the input, typed some letters (not numbers), sent the form, the page was reloaded with the page title (in the tab) saying "Das Formular konnte nicht gesendet werden" (german for "Form could not be sent") and the fieldset was hidden.

Are the conditions possibly only checked on `change`, not on `load`?

**Comment by aschempp** [comment] 2023-11-16 11:12
I'm unable to reproduce this in the latest release (3.1.0). The issue might have been fixed in the changes in this release.

**Closed by aschempp** 2023-11-16 11:12 UTC
