### ISSUE TITLE
Fix the keys of $arrTriggerFields

### ISSUE THREAD

**Issue by Ukgcity** [terminal42/contao-conditionalformfields#37] opened 2020-05-22 08:00 UTC
I've encountered with one issue when added 5+ fieldsets on Contao 3.

See the same issue https://github.com/terminal42/contao-conditionalformfields/issues/32

/conditionalformfields/ConditionalFormFields.php Line 209

function generateJS

Sometimes parameter $arrTriggerFields contains array with unordered keys like that

```
array(
	0=>"Personen",
	1=>"Adresse",
	3=>"AdresseMitreisende1"
)
```

And then json_encode returns

`{"0":"Personen","1":"Adresse","3":"AdresseMitreisende1"}`

instead of

`{"Personen","Adresse","AdresseMitreisende1"}`

Can be checked here https://www.functions-online.com/json_encode.html

And that's why conditional doesn't work.

My suggestion is to add a fixing of array's keys, something like that

`$arrTriggerFields = array_values($arrTriggerFields);`

**Comment by aschempp** [comment] 2020-05-27 20:20
`{"Personen","Adresse","AdresseMitreisende1"}` does not seem a valid JSON string to me?

**Comment by Ukgcity** [comment] 2020-06-04 05:47
You're right, but I mean if we got the array of fields like that

```
array(
	0=>"Personen",
	1=>"Adresse",
	3=>"AdresseMitreisende1"
);
```
and result with

`{"0":"Personen","1":"Adresse","3":"AdresseMitreisende1"}`

Then everything begins not to work.

**Comment by aschempp** [comment] 2020-09-07 12:47
Duplicate of #32 then 🙃

**Closed by aschempp** 2020-09-07 12:47 UTC
